# Generated by Django 5.1.6 on 2025-03-02 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('origination', models.CharField(max_length=64)),
                ('destination_city', models.CharField(max_length=64)),
                ('destination_state', models.CharField(max_length=2)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('taking_passengers', models.BooleanField(default=False)),
                ('seats_available', models.IntegerField(default=0)),
                ('email', models.EmailField(max_length=100)),
                ('vehicle_type', models.CharField(max_length=64)),
            ],
        ),
    ]
